:insert
# ------------------------------------------------
# Version           : 0.1
# Last Change       :
# ------------------------------------------------
# Base system is the Centos version
from centos:centos7

maintainer thmsaurel <thms.aurel@gmail.com>

